server:
  port: 10003
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:
eureka:
  client:
    service-url:
      defaultZone: http://10.12.159.32:8766/eureka/
    register-with-eureka: true
    fetch-registry: false
  server:
      enable-self-preservation: false
      eviction-interval-timer-in-ms: 200000
mybatis:
  type-aliases-package: com.qf.j1902.pojo
  mapper-locations: classpath:mapping/*.xml
